# Copyright 2026 The Taisce Authors
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "taisce.serviceAccount" . }}
  labels: {{- include "taisce.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
