# Copyright 2026 The Taisce Authors
# SPDX-License-Identifier: Apache-2.0
"""Size the qualification topology by the GPUs the node actually exposes.

`compose.gpu.yaml` records the eight-card reference topology: seven generation replicas on
cards 0–6 and the embedding model on card 7. A provider does not always deliver eight cards, and a
four-card VM of the same class is the same environment at half the price. So the reference stays as
written and this writes a third compose file that only narrows it: the load balancer depends on and
routes to the first N−1 replicas, the embedding model moves to card N−1, and the runner starts only
those services. Eight cards reproduce the reference exactly, which is what makes one code path safe.

Workers. Formation drains one project at a time per worker under an advisory lock, and a vLLM replica
batches several sequences. One worker per replica therefore leaves most of a replica's batch slots
idle. Coverage mode runs several workers per replica and deals the corpus over as many projects, so
every replica stays busy; qualification mode keeps one per replica, as D116 measured.

Card memory. The reference assumes 80 GB cards, one replica per card at tensor-parallel size one.
The generation model's BF16 weights are 51.1 GiB, so a 48 GB card cannot hold a replica alone; on
such cards each replica spans two cards at tensor-parallel size two, and the replica count halves.
The command is regenerated from the reference arguments with only the parallel size changed.

Usage: topology.py <gpu_count> [workers_per_replica] [card_memory_gb]  → writes
qualification-topology.yaml and qualification-generation-nginx.conf, prints the sizes as shell
assignments.
"""
import sys
from pathlib import Path

gpus = int(sys.argv[1])
per_replica = int(sys.argv[2]) if len(sys.argv) > 2 else 1
card_gb = int(float(sys.argv[3])) if len(sys.argv) > 3 else 80
tp = 1 if card_gb >= 60 else 2
if gpus < 2:
    raise SystemExit('a node needs at least two cards: one generation replica and the embedding model')
if gpus > 8:
    gpus = 8  # the reference defines seven replica services; more cards stay idle rather than invented
replicas = (gpus - 1) // tp
if replicas < 1:
    raise SystemExit('not enough cards for one generation replica beside the embedding model')
workers = replicas * per_replica
services = [f'generation-{i}' for i in range(replicas)]
embedding_card = replicas * tp
# The reference generation arguments; only the parallel size varies with card memory.
reference_command = ['Qwen/Qwen3.8-27B', '--revision=1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0', '--dtype=bfloat16',
                     f'--tensor-parallel-size={tp}', '--structured-outputs-config.backend=guidance',
                     '--max-model-len=32768', '--max-num-seqs=8', '--gpu-memory-utilization=0.95',
                     '--reasoning-parser=qwen3', '--default-chat-template-kwargs={"enable_thinking":false}',
                     '--ssl-keyfile=/tls/server.key', '--ssl-certfile=/tls/server.crt']

nginx = ['# Generated by deploy/gpu/topology.py; the committed reference is deploy/gpu/generation-nginx.conf.',
         'events {}', '', 'http {', '    upstream generation_replicas {', '        least_conn;']
nginx += [f'        server {s}:8000;' for s in services]
nginx += ['        keepalive 128;', '    }', '', '    server {', '        listen 8000 ssl;',
          '        ssl_certificate /tls/server.crt;', '        ssl_certificate_key /tls/server.key;',
          '        ssl_protocols TLSv1.2 TLSv1.3;', '', '        location / {',
          '            proxy_pass https://generation_replicas;', '            proxy_http_version 1.1;',
          '            proxy_set_header Host generation;', '            proxy_set_header Connection "";',
          '            proxy_ssl_server_name on;', '            proxy_ssl_name generation;',
          '            proxy_ssl_trusted_certificate /tls/ca.crt;', '            proxy_ssl_verify on;',
          '            proxy_connect_timeout 10s;', '            proxy_read_timeout 10m;',
          '            proxy_send_timeout 10m;', '        }', '    }', '}', '']
Path('qualification-generation-nginx.conf').write_text('\n'.join(nginx))

topology = ['# Generated by deploy/gpu/topology.py for a node exposing %d card(s). Never committed.' % gpus,
            'services:', '  generation:', '    depends_on: !override']
topology += [f'      {s}: {{condition: service_healthy}}' for s in services]
topology += ['    volumes: !override',
             '      - ./qualification-generation-nginx.conf:/etc/nginx/nginx.conf:ro',
             '      - ./qualification-tls:/tls:ro',
             '      - ./qualification-tls/ca.crt:/etc/ssl/certs/ca-certificates.crt:ro']
if tp > 1:
    import json
    for i, service in enumerate(services):
        cards = ', '.join('"%d"' % c for c in range(i * tp, (i + 1) * tp))
        topology += [f'  {service}:',
                     '    command: !override ' + json.dumps(reference_command),
                     '    deploy: {resources: {reservations: {devices: !override [{driver: nvidia, device_ids: [%s], capabilities: [gpu]}]}}}' % cards]
topology += ['  embedding:',
             '    deploy: {resources: {reservations: {devices: !override [{driver: nvidia, device_ids: ["%d"], capabilities: [gpu]}]}}}' % embedding_card,
             '']
Path('qualification-topology.yaml').write_text('\n'.join(topology))
print(f'TOPOLOGY_GPUS={gpus} TOPOLOGY_TP={tp} TOPOLOGY_REPLICAS={replicas} TOPOLOGY_WORKERS={workers} '
      f'TOPOLOGY_EMBEDDING_GPU={embedding_card} TOPOLOGY_SERVICES="{" ".join(services)}"')
